package com.arsenii.fitnessapp

// Holds all exercise names and descriptions
object ExerciseDescriptions {
    val descriptions = mapOf(
        "Bench Press" to "Movement: Lie on a bench, lower a barbell to your chest, then press it back up.\nMuscles Targeted: Pectoralis major, anterior deltoids, and triceps.",
        "Squat" to "Movement: Lower your hips from a standing position and then stand back up.\nMuscles Targeted: Quadriceps, glutes, hamstrings, and core.",
        "Deadlift" to "Movement: Lift a loaded barbell off the floor to a standing position, then lower it back down.\nMuscles Targeted: Posterior chain (hamstrings, glutes, back), core, and grip strength.",
        "Overhead Press" to "Movement: Press a barbell or dumbells from your shoulders to overhead.\nMuscles Targeted: Deltoids, triceps, and trapezius.",
        "Barbell Row" to "Movement: Pull a barbell from the floor to your lower chest while hinged at the hips.\nMuscles Targeted: Latissimus dorsi, rhomboids, biceps, and rear deltoids.",
        "Pull-ups" to "Movement: Pull your body up from a hanging position until your chin is over the bar.\nMuscles Targeted: Latissimus dorsi, biceps, and forearms.",
        "Dumbell Curls" to "Movement: Curl dumbells from a hanging position up to your shoulders.\nMuscles Targeted: Biceps.",
        "Triceps Dips" to "Movement: Lower and raise your body using parallel bars.\nMuscles Targeted: Triceps, chest, and anterior deltoids.",
        "Leg Press" to "Movement: Push a weighted platform away from you with your feet.\nMuscles Targeted: Quadriceps, glutes, and hamstrings.",
        "Lunges" to "Movement: Step forward with one leg and lower your hips until both knees are bent at a 90-degree angle.\nMuscles Targeted: Quadriceps, glutes, and hamstrings.",
        "Calf Raises" to "Movement: Raise your heels up and down from a standing position.\nMuscles Targeted: Calves (gastrocnemius and soleus).",
        "Plank" to "Movement: Hold a push-up position, with your body forming a straight line.\nMuscles Targeted: Core (abdominals, obliques, lower back).",
        "Crunches" to "Movement: Lie on your back and lift your upper torso towards your knees.\nMuscles Targeted: Rectus abdominis.",
        "Russian Twists" to "Movement: Sit on the floor, lean back, and twist your torso from side to side.\nMuscles Targeted: Obliques and rectus abdominis.",
        "Lateral Raises" to "Movement: Raise dumbells out to your sides until they are at shoulder level.\nMuscles Targeted: Medial deltoids.",
        "Leg Curls" to "Movement: Curl a weighted lever towards your glutes with your legs.\nMuscles Targeted: Hamstrings.",
        "Leg Extensions" to "Movement: Extend your legs against a weighted lever.\nMuscles Targeted: Quadriceps.",
        "Push-ups" to "Movement: Raise and lower your body with your arms.\nMuscles Targeted: Pectoralis major, deltoids, and triceps.",
        "Lat Pulldowns" to "Movement: Pull a weighted bar down to your chest from an overhead position.\nMuscles Targeted: Latissimus dorsi.",
        "Seated Cable Row" to "Movement: Pull a weighted handle towards your lower abdomen from a seated position.\nMuscles Targeted: Rhomboids, latissimus dorsi, and biceps.",
        "Incline Dumbell Press" to "Movement: Press dumbells from your chest upwards at an incline.\nMuscles Targeted: Upper Pectoralis major, deltoids, and triceps.",
        "Dumbell Flyes" to "Movement: With a slight bend in your elbows, lower dumbells to your sides, then bring them back up over your chest.\nMuscles Targeted: Pectoralis major.",
        "Face Pulls" to "Movement: Pull a rope towards your face, keeping your upper arms parallel to the floor.\nMuscles Targeted: Rear deltoids and upper back.",
        "Hammer Curls" to "Movement: Curl dumbells with a neutral grip (palms facing each other).\nMuscles Targeted: Biceps and brachialis.",
        "Cable Crossover" to "Movement: From a standing position, bring cables from out to your sides to in front of your chest.\nMuscles Targeted: Pectoralis major.",
        "Dumbell Pullover" to "Movement: Lying on a bench, lower a dumbell behind your head, then pull it back over your chest.\nMuscles Targeted: Latissimus dorsi and pectoralis major.",
        "T-Bar Row" to "Movement: Pull a weighted T-bar towards your chest from a hinged position.\nMuscles Targeted: Latissimus dorsi, rhomboids, and biceps.",
        "Single-Arm Dumbell Row" to "Movement: Supporting your body with one arm on a bench, row a dumbell up to your side.\nMuscles Targeted: Latissimus dorsi, rhomboids, and biceps.",
        "Romanian Deadlift" to "Movement: Hinging at the hips, lower a barbell down your legs, keeping your back straight.\nMuscles Targeted: Hamstrings and glutes.",
        "Hack Squat" to "Movement: Using a hack squat machine, lower your body by bending your knees, then press back up.\nMuscles Targeted: Quadriceps.",
        "Walking Lunges" to "Movement: Step forward into a lunge, then immediately step forward with the other leg into another lunge.\nMuscles Targeted: Quadriceps and glutes.",
        "Seated Dumbell Shoulder Press" to "Movement: From a seated position, press dumbells from your shoulders to overhead.\nMuscles Targeted: Deltoids and triceps.",
        "Arnold Press" to "Movement: A rotational shoulder press, starting with palms facing you and ending with palms facing away.\nMuscles Targeted: All three heads of the deltoids.",
        "Shrugs" to "Movement: From a standing position, elevate your shoulders towards your ears, holding a barbell or dumbells.\nMuscles Targeted: Trapezius.",
        "Preacher Curls" to "Movement: Using a preacher bench, curl a barbell or dumbells towards your shoulders.\nMuscles Targeted: Biceps.",
        "Skull Crushers" to "Movement: Lying on a bench, lower a barbell towards your forehead, then extend your arms back up.\nMuscles Targeted: Triceps.",
        "Triceps Pushdown" to "Movement: Using a cable machine, push a bar down until your arms are fully extended.\nMuscles Targeted: Triceps.",
        "Incline Bench Press" to "Movement: Lying on an incline bench, press a barbell or dumbells from your chest upwards.\nMuscles Targeted: Upper pectoralis major and anterior deltoids.",
        "Decline Bench Press" to "Movement: Lying on a decline bench, press a barbell or dumbells from your chest upwards.\nMuscles Targeted: Lower pectoralis major.",
        "Good Mornings" to "Movement: With a barbell on your back, hinge at the hips and lower your torso until it\'s parallel to the floor.\nMuscles Targeted: Hamstrings, glutes, and lower back.",
        "Hyperextensions" to "Movement: Using a hyperextension bench, bend at the waist and then raise your upper body until it\'s in line with your lower body.\nMuscles Targeted: Lower back and glutes.",
        "Front Raises" to "Movement: From a standing position, raise dumbells in front of you to shoulder level.\nMuscles Targeted: Anterior deltoids.",
        "Goblet Squat" to "Movement: Holding a dumbell or kettlebell in front of your chest, squat down until your hips are below your knees.\nMuscles Targeted: Quadriceps and glutes.",
        "Bulgarian Split Squat" to "Movement: With one foot elevated behind you on a bench, squat down on your front leg.\nMuscles Targeted: Quadriceps and glutes.",
        "Chin-ups" to "Movement: Similar to a pull-up, but with an underhand grip.\nMuscles Targeted: Biceps and latissimus dorsi.",
        "Diamond Push-ups" to "Movement: A push-up with your hands close together, forming a diamond shape.\nMuscles Targeted: Triceps and pectoralis major.",
        "Dumbell Bench Press" to "Movement: Lying on a bench, press dumbells up from your chest.\nMuscles Targeted: Pectoralis major, anterior deltoids, and triceps.",
        "Upright Row" to "Movement: From a standing position, pull a barbell or dumbells up to your chin.\nMuscles Targeted: Deltoids and trapezius.",
        "Close-Grip Bench Press" to "Movement: A bench press with a narrow grip to emphasize the triceps.\nMuscles Targeted: Triceps and pectoralis major.",
        "Bent Over Dumbell Row" to "Movement: Hinging at the hips, pull dumbells up to your sides.\nMuscles Targeted: Latissimus dorsi, rhomboids, and biceps.",
        "Concentration Curl" to "Movement: Seated on a bench, curl a dumbell from a hanging position with your elbow braced against your inner thigh.\nMuscles Targeted: Biceps.",
        "Reverse Pec-Deck" to "Movement: Using a pec-deck machine, move your arms from in front of you to out to your sides.\nMuscles Targeted: Rear deltoids.",
        "Sissy Squat" to "Movement: A bodyweight squat variation that emphasizes the quadriceps.\nMuscles Targeted: Quadriceps.",
        "Glute Bridge" to "Movement: Lying on your back, thrust your hips upwards.\nMuscles Targeted: Glutes and hamstrings.",
        "Seated Calf Raise" to "Movement: From a seated position, raise your heels up and down.\nMuscles Targeted: Soleus (calf)."
    )
}
